// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuvysdrckdlakgqutyqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dnlzZHJja2RsYWtncXV0eXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjIxNDMsImV4cCI6MjA3Mjc5ODE0M30.W-Gn8w60oqqqVLBgHcy3cbsqGo-fYYEw3jqtxDGJuFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});